export const env = {
  EXPO_PUBLIC_BACKEND_URL: process.env.EXPO_PUBLIC_BACKEND_URL!,
  EXPO_PUBLIC_WEBSOCKET_URL: process.env.EXPO_PUBLIC_WEBSOCKET_URL!,
  EXPO_PUBLIC_DH_GN: process.env.EXPO_PUBLIC_DH_GN!,
};
